### ISSUE TITLE
No such file or directory: 'causalinference/utils/vignette_data.txt'

### ISSUE THREAD

**Issue by lincolnfrias** [laurencium/Causalinference#1]
Following the blog posts, when I do

    from causalinference.utils import vignette_data
    Y, D, X = vignette_data()

I get

> No such file or directory: 'causalinference/utils/vignette_data.txt'

Just a minor issue. The library is very elegant and has been **extremely** helpful. Thanks a lot.

**Comment by laurencium** [comment]
Just fixed this issue and updated everything. You should be able to just do a `pip install --upgrade causalinference` and have this working properly. Thanks for finding the bug!

**Comment by lincolnfrias** [comment]
Great, thanks.
