### ISSUE TITLE
how to retrieve the matched observations?

### ISSUE THREAD

**Issue by lincolnfrias** [laurencium/Causalinference#2]
Is there a way to access `matches_c` and `matches_t` objects?

**Comment by laurencium** [comment]
No simple way without modifying the code unfortunately. The `matches_c` and `matches_t` objects are not very self-explanatory so I didn't bother making them accessible. If you'd like to access them the easiest way is probably to stick in a `self.` in front of the lines where they are created. Preserving them in `self._dict` is another possibility.

**Comment by lincolnfrias** [comment]
Ok, I'll try that,
