### ISSUE TITLE
What is the best way to do propensity score matching?

### ISSUE THREAD

**Issue by lincolnfrias** [laurencium/Causalinference#3]
Should I use a two-step process like this?

    causal = CausalModel(Y, D, X)
    causal.est_propensity_s()
    ps = causal.propensity['fitted']

    causal2 = CausalModel(Y, D, ps)
    causal2.est_via_matching(bias_adj=True)
    print(causal2.estimates)

**Comment by laurencium** [comment]
Hah! Never thought about using it this way but this should work. Another way is simply to stratify the sample and use the blocking estimator. The stratification is based on the estimated propensity score (so every block contains units with similar p scores), and the blocking estimator estimates and aggregates the within-bin treatment effects properly. Often when people say propensity score matching they really mean this approach!

**Comment by lincolnfrias** [comment]
I guess you are right. Testing with your simulated data, my strategy leads to very poor results . Thanks for your kindness. Best.
