### ISSUE TITLE
Any way to infer causal effects for individual units?

### ISSUE THREAD

**Issue by NataliaVConnolly** [laurencium/Causalinference#7]
Hi,
   This may be a naive question, but I was just wondering if there's a way to extract the probability that "treatment Z caused outcome Y" user by user, not on average for a treated cohort vs. untreated one?

**Comment by laurencium** [comment]
Short answer is no, as those aren't statistically speaking good estimates. You may, however, find code in, e.g., [matching.py](https://github.com/laurencium/Causalinference/blob/master/causalinference/estimators/matching.py), that computes individual treatment effects as an intermediate step useful for reference.
